### ISSUE TITLE
support for commands (in addition to broadcast)

### ISSUE THREAD

**Issue by mshuflin** [ismarslomic/google-assistant-broadcast#2]
Other similar projects have exposed a /broadcast and /command endpoint. Is it possible to do this?

reference: https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/46

Thank you for this! Yours is the only one I was able to get authenticated, and all other similar projects appear to be unmaintained.

**Comment by ismarslomic** [comment]
Glad you find this project useful @mshuflin! While I'm aware of that the Google Assistant Service API supports commands, in addition to message broadcasting, I wanted to narrow this project to _broadcasting_ specifically, hence the project name "google-assistant-broadcast". This is basically because I use this project myself and thus have incentive to maintain it. I control my smart home through Home Assistant and don't have use cases to send commands to Google Assistant. Sorry to disappoint you, but I hope this strategy can make sure that this project is being maintained and will be useful for other users as well going forward.
