### ISSUE TITLE
Sending message [OK] Conversation Response:  empty No sound or message played on the speakers

### ISSUE THREAD

**Issue by aguscaba** [ismarslomic/google-assistant-broadcast#9]
Hi, first of all I want to thank you for this tool, I hope I can use it,

I know this is an know issue but tried with the provided solutions without success

No issues on getting the auth up after that tried the solutions published on the Known issues section but Still no sound is played, the way I finally started my docker instance is:

`docker run --name google-assistant-broadcast \
-p 8085:8085 \
-e LANGUAGE=es-MX \
-v /softw/app/docker/google-assistant-oauth/config:/usr/src/config \
ismarslomic/google-assistant-broadcast:latest`

On the docker side it prints:

`[2022-08-21T19:57:39.923Z] Sending message (es-MX): Broadcast Hola
[2022-08-21T19:57:42.343Z] [OK] Conversation Response:  empty
[2022-08-21T19:57:42.516Z] [OK] Conversation Completed`

The curl I am using:

`curl -X POST http://localhost:8085/broadcast  -d '{"message":"Hola"}'  -H "Content-Type: application/json"`

The response:

`{"response":"empty"}`

Please any help would be appreciated.

**Comment by ismarslomic** [comment]
I'm really empty with suggestions. These kind of issues are hard to analyze, since there are no error response from Google Assistant and the service behaves somehow differently in every country. You might try to generate completely new OAuth Client file from GCP Console / API & Services / Credentials page (not from Google Actions Console), read solution on issue https://github.com/ismarslomic/google-assistant-broadcast/issues/7#issuecomment-1151601639 and publish your project to production as described in #8

**Comment by ismarslomic** [comment]
Closing this issue as there have not been any updates for the last 9 days. Please add a comment if you find a solution, so it can be useful for other users.
